// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojopLjrR2b01YGbxKsVhnpfWpSb_r5Hk',
    appId: '1:956446621585:android:336c35e3f971f73b90a430',
    messagingSenderId: '956446621585',
    projectId: 'riv-todo-adv-example',
    storageBucket: 'riv-todo-adv-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBea2tZ-svKr98qViJS7H1w6MrU-OglgfQ',
    appId: '1:956446621585:ios:8e3f6515e79b069190a430',
    messagingSenderId: '956446621585',
    projectId: 'riv-todo-adv-example',
    storageBucket: 'riv-todo-adv-example.appspot.com',
    iosBundleId: 'com.example.rivTodoAdvExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBea2tZ-svKr98qViJS7H1w6MrU-OglgfQ',
    appId: '1:956446621585:ios:6f8c70320bc5f3e490a430',
    messagingSenderId: '956446621585',
    projectId: 'riv-todo-adv-example',
    storageBucket: 'riv-todo-adv-example.appspot.com',
    iosBundleId: 'com.example.rivTodoAdvExample.RunnerTests',
  );
}
